name: Node.js Package

on:
  push:
    branches:
      - is

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm test
  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
         - echo email=${{secrets.mail}} > .npmrc
         - echo always-auth=true >> .npmrc
         - echo _auth=${{secrets.npm_token}}>>.npmrc
         - npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
